### ISSUE TITLE
sentiment.py

### ISSUE THREAD

**Issue by AKBoles** [pwolfe8/EmotionProject#1]
Hey man, great project. Was looking through it and noticed that `sentiment.py` needs an equal sign in the `model.fit` portion after `validation_set`. Just thought you should know!

**Comment by pwolfe8** [comment]
Oh okay, thanks! Yeah I'm currently in the middle of trying to finish this project for a final project for our ML class that's due in about 2 weeks. this was just a tutorial I followed to get started from Siraj on youtube and seems like i copied it wrong or he might've had some different version: https://www.youtube.com/watch?v=si8zZHkufRY&t=335s
Thanks!

**Comment by AKBoles** [comment]
Awesome! I know it was a small fix but one I noticed. I found your repo and was interested because I am doing research on emotion detection for the lab I work in at my university! Very nice project, will be keeping tabs on it. Good luck on finishing! All the best.
